FROM wanguolin/comfly:comfy-cli-ubuntu24.04-python3.11-cpu

WORKDIR /root/comfy

COPY workflows /root/comfy/workflows
RUN /bin/sh -c ". venv/bin/activate && \
    find /root/comfy/workflows -name '*.json' -type f -exec echo 'Processing {}' \; -exec comfy node install-deps --workflow {} \;"

#post install
RUN /bin/sh -c ". venv/bin/activate && pip install evalidate"

ENTRYPOINT ["/bin/sh", "-c", ". /root/comfy/venv/bin/activate && python /root/comfy/ComfyUI/main.py --listen 0.0.0.0 --port 8188 --cpu"]
