name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy workflows directory
      working-directory: infra/docker/comfly-cli-base/cpu
      run: cp -r $GITHUB_WORKSPACE/workflows .

    - name: Build Docker image
      working-directory: infra/docker/comfly-cli-base/cpu
      run: docker build -f Dockerfile.comfy-cli-install-workflows -t wanguolin/comfly:comfy-cli-install-workflows .

    - name: Push Docker image
      if: success() 
      working-directory: infra/docker/comfly-cli-base/cpu
      run: docker push wanguolin/comfly:comfy-cli-install-workflows
  