name: Build and Push Docker Image

on:
  workflow_dispatch:  # manually trigger

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: comfy-cli-workflows-pre-install  # 定义环境变量

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy workflows directory
      run: cp -r workflows infra/docker/comfy-cli-base/cpu

    - name: Build Docker image
      working-directory: infra/docker/comfy-cli-base/cpu
      run: docker build -f Dockerfile.${{ env.IMAGE_TAG }} -t wanguolin/comfly:${{ env.IMAGE_TAG }} .

    - name: Push Docker image
      if: success() 
      working-directory: infra/docker/comfy-cli-base/cpu
      run: docker push wanguolin/comfly:${{ env.IMAGE_TAG }}
